### ISSUE TITLE
Direct-leak (7520)

### ISSUE THREAD

**Issue by dlemstra** [glennrp/libpng#220]
The @ImageMagick project is using https://github.com/google/oss-fuzz to find bugs in our own library and in libraries that we use. The fuzzer found an issue and we think this is an issue that should be resolved in the library that we use. This issue is posted under the url https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=7520 that is not publicly visible yet but added as a link for future reference. Below are the details of the issue that can be reproduced using the following technique: https://github.com/google/oss-fuzz/blob/master/docs/reproducing.md

Stacktrace:
```
==1==ERROR: LeakSanitizer: detected memory leaks
--
  |  
  | Direct leak of 12 byte(s) in 1 object(s) allocated from:
  | #0 0x4ea798 in malloc _asan_rtl_
  | #1 0xbccc7d in png_malloc_warn libpng/pngmem.c:217:23
  | #2 0xbfc60a in png_handle_eXIf libpng/pngrutil.c:2065:25
  | #3 0xbcd35c in png_read_info libpng/pngread.c:180:10
  | #4 0xb09324 in ReadOnePNGImage imagemagick/coders/png.c:2536:3
  | #5 0xaf1f65 in ReadPNGImage imagemagick/coders/png.c:4254:9
  | #6 0x6cbb78 in ReadImage imagemagick/MagickCore/constitute.c:500:13
  | #7 0x6669f5 in BlobToImage imagemagick/MagickCore/blob.c:469:13
  | #8 0x5b28f2 in Magick::Image::read(Magick::Blob const&) imagemagick/Magick++/lib/Image.cpp:4015:12
  | #9 0x526a1f in LLVMFuzzerTestOneInput imagemagick/Magick++/fuzz/encoder_fuzzer.cc:46:11
  | #10 0x5506d1 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:517:13
  | #11 0x52787a in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/libfuzzer/FuzzerDriver.cpp:280:6
  | #12 0x53312b in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:703:9
  | #13 0x526f1c in main /src/libfuzzer/FuzzerMain.cpp:20:10
  | #14 0x7fa21121582f in __libc_start_main /build/glibc-Cl5G7W/glibc-2.23/csu/libc-start.c:291
  |  
  | SUMMARY: AddressSanitizer: 12 byte(s) leaked in 1 allocation(s).
```

Links:
https://github.com/glennrp/libpng/blob/916117d97058b37e7eef2558a71919a8a073a3d3/pngmem.c#L217

Commit: 916117d97058b37e7eef2558a71919a8a073a3d3
Testcase file: [clusterfuzz-testcase-minimized-encoder_png_fuzzer-5108894633295872.zip](https://github.com/glennrp/libpng/files/1908866/clusterfuzz-testcase-minimized-encoder_png_fuzzer-5108894633295872.zip)

Analysis:
The attached png file contains 2 exif chunks and the first the method exists here: https://github.com/glennrp/libpng/blob/916117d97058b37e7eef2558a71919a8a073a3d3/pngrutil.c#L2091-L2092 The second time the eXIf_buf is overwritten with the following malloc: https://github.com/glennrp/libpng/blob/916117d97058b37e7eef2558a71919a8a073a3d3/pngrutil.c#L2065-L2066

**Comment by alalek** [comment]
Confirmed.
Another one related oss-fuzz issue: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=13314

**Comment by alalek** [comment]
BTW, buffer cleanup was in that place in 2017: https://github.com/glennrp/libpng/commit/71a56180e54de5ffa42b7e85835c272771393add#diff-6b2a2c08b86b9ca2566040b914e34576L2043

**Comment by jbowler** [comment]
@ctruta the early exit on a CRC failure reported above has been corrected.  The test on png_crc_finish is reversed (to success) and the call to png_set_eXIf_1 is now protected by that.  info_ptr->eXIf_buf (which is really a local variable; it's just there because of setjmp on a png_error) should now be reliably freed.

The code is horrible (using a member of png_info to store a temporary allocation of memory and, indeed, using a temporary allocation in the first place) is something I consider a bug but it's not one that needs fixing here.
