### ISSUE TITLE
pngfix: contrib/tools/pngfix.c:323: uarb_mult32: Assertion `a_digits > 0' failed.

### ISSUE THREAD

**Issue by geeknik** [glennrp/libpng#37]
I just compiled libpng from git source and am fuzzing pngfix with American Fuzzy Lop and I came across a "png" (https://dl.dropboxusercontent.com/u/6088006/libpng/test00.png) that causes an assertion failure.

```
~/libpng/pngfix --strip=all test00.png
pngfix: contrib/tools/pngfix.c:323: uarb_mult32: Assertion `a_digits > 0' failed.
Aborted
```

```
Starting program: /home/geeknik/libpng/pngfix --strip=all test00.png
pngfix: contrib/tools/pngfix.c:323: uarb_mult32: Assertion `a_digits > 0' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff754c107 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff754c107 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff754d4e8 in __GI_abort () at abort.c:89
#2  0x00007ffff7545226 in __assert_fail_base (
    fmt=0x7ffff767bce8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x52cde0 "a_digits > 0", 
    file=file@entry=0x52cdae "contrib/tools/pngfix.c", line=line@entry=323, 
    function=function@entry=0x52dcd2 <__PRETTY_FUNCTION__.5982> "uarb_mult32")
    at assert.c:92
#3  0x00007ffff75452d2 in __GI___assert_fail (
    assertion=assertion@entry=0x52cde0 "a_digits > 0", 
    file=file@entry=0x52cdae "contrib/tools/pngfix.c", line=line@entry=323, 
    function=function@entry=0x52dcd2 <__PRETTY_FUNCTION__.5982> "uarb_mult32")
    at assert.c:101
#4  0x0000000000409441 in uarb_mult32 (acc=<optimized out>, 
    a_digits=<optimized out>, num=<optimized out>, n_digits=<optimized out>, 
    val=<optimized out>) at contrib/tools/pngfix.c:323
#5  0x00000000004179fb in calc_image_size (file=0x7fffffffd040)
    at contrib/tools/pngfix.c:1500
#6  process_chunk (file=file@entry=0x7fffffffd040, file_crc=<optimized out>, 
    next_length=<optimized out>, next_type=<optimized out>)
    at contrib/tools/pngfix.c:2904
#7  0x000000000041a4be in sync_stream (file=<optimized out>)
    at contrib/tools/pngfix.c:3039
---Type <return> to continue, or q <return> to quit---
#8  read_chunk (file=file@entry=0x7fffffffd040) at contrib/tools/pngfix.c:3162
#9  0x000000000041bd98 in read_callback (png_ptr=0x73c250, 
    buffer=0x7fffffffcee0 "\340\317\377\377\377\177", count=8)
    at contrib/tools/pngfix.c:3283
#10 0x00000000004c8338 in png_read_chunk_header (
    png_ptr=png_ptr@entry=0x73c250) at pngrutil.c:168
#11 0x000000000045ca68 in png_read_info (png_ptr=0x73c250, info_ptr=0x73c740)
    at pngread.c:108
#12 0x0000000000474019 in png_read_info (png_ptr=<optimized out>, 
    info_ptr=<optimized out>) at pngread.c:254
#13 0x0000000000401bed in read_png (control=0x7fffffffd040)
    at contrib/tools/pngfix.c:3618
#14 0x0000000000404449 in one_file (out_name=<optimized out>, 
    file_name=<optimized out>, global=<optimized out>)
    at contrib/tools/pngfix.c:3666
#15 main (argc=1, argv=0x7fffffffe368) at contrib/tools/pngfix.c:4008
(gdb) i r
rax            0x0	0
rbx            0x7ffff7ff4000	140737354088448
rcx            0xffffffffffffffff	-1
rdx            0x6	6
rsi            0x136b0	79536
rdi            0x136b0	79536
rbp            0x7ffff767bce8	0x7ffff767bce8
rsp            0x7fffffffcbc8	0x7fffffffcbc8
r8             0xfefefefefefefe00	-72340172838076928
r9             0x73c8a0	7588000
r10            0x8	8
r11            0x246	582
r12            0x52cde0	5426656
r13            0x52dcd2	5430482
r14            0x3	3
r15            0x4	4
rip            0x7ffff754c107	0x7ffff754c107 <__GI_raise+55>
eflags         0x246	[ PF ZF IF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0
```

**Comment by geeknik** [comment]
This issue is still present in the current git source.

**Comment by glennrp** [comment]
Please try libpng-1.6.21rc02 (head of the libpng16 branch of the libpng GIT
repos).
The assert() was misplaced.

Glenn
