### ISSUE TITLE
pngfix: contrib/tools/pngfix.c:2708: zlib_check: Assertion `test_bits == 15' failed

### ISSUE THREAD

**Issue by geeknik** [glennrp/libpng#38]
I just compiled libpng from git source and am fuzzing pngfix with American Fuzzy Lop and I came across a "png" (https://dl.dropboxusercontent.com/u/6088006/libpng/test01.png) that causes an assertion failure.

```
~/libpng/pngfix --strip=all test01.png
pngfix: contrib/tools/pngfix.c:2708: zlib_check: Assertion `test_bits == 15' failed.
Aborted
```

```
Starting program: /home/geeknik/libpng/pngfix --strip=all test01.png
pngfix: contrib/tools/pngfix.c:2708: zlib_check: Assertion `test_bits == 15' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff754c107 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff754c107 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff754d4e8 in __GI_abort () at abort.c:89
#2  0x00007ffff7545226 in __assert_fail_base (
    fmt=0x7ffff767bce8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x52cf42 "test_bits == 15", 
    file=file@entry=0x52cdae "contrib/tools/pngfix.c", line=line@entry=2708, 
    function=function@entry=0x52dcaf <__PRETTY_FUNCTION__.6586> "zlib_check")
    at assert.c:92
#3  0x00007ffff75452d2 in __GI___assert_fail (
    assertion=assertion@entry=0x52cf42 "test_bits == 15", 
    file=file@entry=0x52cdae "contrib/tools/pngfix.c", line=line@entry=2708, 
    function=function@entry=0x52dcaf <__PRETTY_FUNCTION__.6586> "zlib_check")
    at assert.c:101
#4  0x00000000004103c5 in zlib_check (file=file@entry=0x7fffffffd040, 
    offset=offset@entry=0) at contrib/tools/pngfix.c:2708
#5  0x0000000000411302 in process_IDAT (file=0x7fffffffd040)
    at contrib/tools/pngfix.c:1968
#6  process_chunk (file=file@entry=0x7fffffffd040, file_crc=<optimized out>, 
    next_length=808464432, next_type=1682263620) at contrib/tools/pngfix.c:2924
#7  0x000000000041a4be in sync_stream (file=<optimized out>)
    at contrib/tools/pngfix.c:3039
#8  read_chunk (file=file@entry=0x7fffffffd040) at contrib/tools/pngfix.c:3162
#9  0x000000000041bd98 in read_callback (png_ptr=0x73c250, 
    buffer=0x7fffffffcee0 "RDHI", count=8) at contrib/tools/pngfix.c:3283
#10 0x00000000004c8338 in png_read_chunk_header (
    png_ptr=png_ptr@entry=0x73c250) at pngrutil.c:168
#11 0x000000000045ca68 in png_read_info (png_ptr=0x73c250, info_ptr=0x73c740)
    at pngread.c:108
#12 0x0000000000474019 in png_read_info (png_ptr=<optimized out>, 
    info_ptr=<optimized out>) at pngread.c:254
#13 0x0000000000401bed in read_png (control=0x7fffffffd040)
    at contrib/tools/pngfix.c:3618
#14 0x0000000000404449 in one_file (out_name=<optimized out>, 
    file_name=<optimized out>, global=<optimized out>)
    at contrib/tools/pngfix.c:3666
#15 main (argc=1, argv=0x7fffffffe368) at contrib/tools/pngfix.c:4008
(gdb) i r
rax            0x0	0
rbx            0x7ffff7ff4000	140737354088448
rcx            0xffffffffffffffff	-1
rdx            0x6	6
rsi            0x1e47d	124029
rdi            0x1e47d	124029
rbp            0x7ffff767bce8	0x7ffff767bce8
rsp            0x7fffffffcac8	0x7fffffffcac8
r8             0xfefefefefefefe00	-72340172838076928
r9             0x74e4b0	7660720
r10            0x8	8
r11            0x246	582
r12            0x52cf42	5427010
r13            0x52dcaf	5430447
r14            0x11	17
r15            0x7fffffffcd00	140737488342272
rip            0x7ffff754c107	0x7ffff754c107 <__GI_raise+55>
eflags         0x246	[ PF ZF IF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0
```

**Comment by jbowler** [comment]
The zlib stream contains a CMINFO of 9 which results in an out of range value for the window bits which the assert then catches.  Harmless problem although maybe some files with this error could be fixed if there are no more errors in the stream.

The fix is in https://github.com/jbowler/libpng-1/tree/libpng16-20

**Comment by glennrp** [comment]
pngfix has been patched in libpng16 and libpng17 branches, and in the libpng-1.6.20rc01 tarball.
